### ISSUE TITLE
타입스크립트 린트 플러그인 추가

### ISSUE THREAD

**Issue by minsour** [mash-up-kr/mash-up-admin-fe#26]
타입스크립트 린트 플러그인이 추가되어 있지 않아서 interface에서 함수 정의 시 타입으로 보지 않아서 린트 에러 발생

TODO: eslint-disable-next-line no-unused-vars 제거

**Comment by dididy** [comment]
https://github.com/mash-up-kr/mash-up-admin-fe/pull/24/commits/eb8775100236b03134137efdf03fecabe279e4db

[@typescript-eslint/no-unused-vars](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-unused-vars.md) 로 해결했습니다!
